### PR TITLE
🕚 Citrix IIT G 2019

### PR DESCRIPTION
**Pull request by rajat1433**
Please find the question above asked by citrix in IITG

### CODE REVIEW

**Comment by kaushal02** [comment]
I don't get it. Wouldn't the solution be to directly print out all 1s followed by all 0s? Why are you using recursion?

**Comment by rajat1433** [comment]
In the problem statement its mentioned that we can only swap 2 special substrings.
And definition of special strings are also given so according to that recursion or dp is the only way.
Since constraints were small recursion passes.

**Comment by rajat1433** [comment]
For eg.
input: s = "11011000"
output: "11100100"
10 swapped with 1100

**Comment by kaushal02** [comment]
No.

s = "11011000"
--- swap s[1,3] and s[4,4]
s = "11101000"
--- swap s[1,4] and s[5,5]
s = "11110000"

Your output is wrong.

**Comment by kaushal02** [comment]
In essence, following code is correct:

```
string makeLargestSpecial(string S) {
    string ans;
    int n = S.size();
    for (int i = 0; i < n / 2; i++) {
        ans += '1';
    }
    for (int i = 0; i < n / 2; i++) {
        ans += '0';
    }
    return ans;
}
```

**Comment by rajat1433** [comment]
I think you did not read the problem statement carefully!!
Its given that: A special string should have these properties:
The number of 0's is equal to the number of 1's.
Every prefix of the binary string has at least as many 1's as 0's.

'''
s = "11011000"
--- swap s[1,3] and s[4,4]
s = "11101000"
--- swap s[1,4] and s[5,5]
s = "11110000"
'''
You are not using these properties into account while swapping!!

**Comment by kaushal02** [comment]
I'm sorry! Go ahead with your solution please. I am assuming it's correct and runs.

**Comment by rajat1433** [comment]
You can revert back and merge in your branch I guess.

**Review by kaushal02 — APPROVED** [review]

**Comment by rajat1433** [comment]
Buddy you have pushed the wrong code in ur repo,🤦 I think you forgot to revert the changes you made

**Comment by kaushal02** [comment]
Can you raise another request?
--
Kaushal Agrawal

**Comment by rajat1433** [comment]
Ok

**Pull request merged**
